import type { CodeMemoryDB } from '../db/database.js';
import { MermaidGenerator } from './mermaid.js';

export type ExportFormat = 'json' | 'mermaid' | 'markdown';

export class CodebaseExporter {
  private readonly db: CodeMemoryDB;
  private readonly mermaid: MermaidGenerator;

  constructor(db: CodeMemoryDB) {
    this.db = db;
    this.mermaid = new MermaidGenerator(db);
  }

  public export(format: ExportFormat): string {
    switch (format) {
      case 'json':
        return this.exportJSON();
      case 'mermaid':
        return this.mermaid.generateArchitectureDiagram();
      case 'markdown':
        return this.exportMarkdown();
      default:
        throw new Error(`Unsupported export format: ${format}`);
    }
  }

  private exportJSON(): string {
    const files = this.db.getAllFiles();
    const metrics = this.db.getCodebaseMetrics();
    const hotspots = this.db.getHotspots(50);
    const hotspotSet = new Set(hotspots.map((h) => h.path));

    const nodes: Record<string, any> = {};
    const edges: Array<any> = [];

    for (const file of files) {
      const symbols = this.db.getSymbolsForFile(file.path);
      const dependencies = this.db.getDependenciesForFile(file.path);

      nodes[file.path] = {
        label: file.path,
        metadata: {
          id: file.id,
          language: file.language,
          size_bytes: file.sizeBytes,
          last_modified: file.lastModified,
          is_hotspot: hotspotSet.has(file.path),
          symbols_count: symbols.length,
          symbols: symbols.map((s) => ({
            id: s.id,
            name: s.name,
            kind: s.kind,
            signature: s.signature,
            line_start: s.lineStart,
            line_end: s.lineEnd,
          })),
        },
      };

      for (const dep of dependencies) {
        edges.push({
          source: dep.sourcePath,
          target: dep.targetPath,
          relation: 'imports',
          directed: true,
          metadata: {
            import_path: dep.importPath,
            symbol_name: dep.targetSymbolName,
          },
        });
      }
    }

    const jgfData = {
      graph: {
        id: 'codememory-architecture-graph',
        type: 'CodebaseArchitecture',
        label: 'CodeMemory Intelligence Graph',
        directed: true,
        metadata: {
          schema_version: '2.0.0',
          generator: '@eldrex/codememory',
          exported_at: new Date().toISOString(),
          metrics: {
            total_files: metrics.totalFiles,
            total_symbols: metrics.totalSymbols,
            total_dependencies: metrics.totalDependencies,
            languages: metrics.languages,
            symbol_kinds: metrics.symbolKinds,
          },
        },
        nodes,
        edges,
      },
      schemaVersion: 1,
      exportedAt: new Date().toISOString(),
      metrics,
      files: files.map((file) => {
        const symbols = this.db.getSymbolsForFile(file.path);
        const dependencies = this.db.getDependenciesForFile(file.path);
        return {
          ...file,
          symbols,
          dependencies,
        };
      }),
    };

    return JSON.stringify(jgfData, null, 2);
  }

  private exportMarkdown(): string {
    const metrics = this.db.getCodebaseMetrics();
    const files = this.db.getAllFiles();
    const mermaidDiagram = this.mermaid.generateArchitectureDiagram();

    const lines: string[] = [];
    lines.push('# Codebase Architecture & Intelligence Map');
    lines.push(`*Generated by CodeMemory at ${new Date().toUTCString()}*\n`);

    lines.push('## 📊 Repository Metrics');
    lines.push(`- **Total Files**: ${metrics.totalFiles}`);
    lines.push(`- **Total Symbols**: ${metrics.totalSymbols}`);
    lines.push(`- **Total Dependencies**: ${metrics.totalDependencies}`);
    lines.push('\n### Languages');
    for (const [lang, count] of Object.entries(metrics.languages)) {
      lines.push(`- **${lang}**: ${count} files`);
    }

    lines.push('\n## 🏗️ Architecture Diagram');
    lines.push(mermaidDiagram);

    lines.push('\n## 📦 File & Symbol Index');
    for (const file of files) {
      lines.push(`\n### \`${file.path}\` (${file.language})`);
      const symbols = this.db.getSymbolsForFile(file.path);
      if (symbols.length === 0) {
        lines.push('*No public symbols detected.*');
      } else {
        lines.push('| Symbol | Kind | Line | Signature |');
        lines.push('| :--- | :--- | :--- | :--- |');
        for (const s of symbols) {
          const sig = s.signature ? `\`${s.signature.replace(/\|/g, '\\|')}\`` : '-';
          lines.push(`| **${s.name}** | \`${s.kind}\` | L${s.lineStart}-${s.lineEnd} | ${sig} |`);
        }
      }
    }

    return lines.join('\n');
  }
}
